name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Format check
        run: yarn format:check

      - name: Lint
        run: yarn lint

      - name: Type check
        run: yarn typecheck

      - name: Build
        run: yarn build

      - name: Check changes
        run: yarn checkchange
        if: ${{ !(startsWith(github.head_ref, 'version-bump-') && github.actor == 'altinokdarici') }}
