name: Version Bump

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version-bump:
    name: Create Version Bump PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Configure git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Action"

      - name: Create version bump PR
        run: |
          # Check if there are any change files
          if [ -d "change" ] && [ "$(ls -A change)" ]; then
            # Create a new branch for version bump
            BRANCH_NAME="version-bump-$(date +%s)"
            git checkout -b "$BRANCH_NAME"

            # Run beachball bump to update versions
            yarn bump

            # Check if there are changes to commit
            if git diff --quiet; then
              echo "No version changes to commit"
              exit 0
            fi

            # Commit and push changes
            git add .
            git commit -m "Bump package versions [skip ci]"
            git push origin "$BRANCH_NAME"

            # Create PR
            gh pr create \
              --title "Release: Bump package versions" \
              --body "Automated version bump created by beachball. This PR contains version updates and changelog entries." \
              --head "$BRANCH_NAME" \
              --base main
          else
            echo "No change files found, skipping version bump"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}